#!/usr/bin/env bash

# Simple stand-alone wrapper for rofi-power-menu.
#
# This script takes the same CLI arguments as rofi-power-menu.

# Use rofi if dmenu isn't found
command -v dmenu >/dev/null
dmenu_exists=$?
if [ $dmenu_exists -eq 0 ]
then
    dmenu="dmenu"
else
    dmenu="rofi -dmenu"
fi

command -v ./rofi-power-menu >/dev/null
powermenu_exists=$?
if [ $powermenu_exists -eq 0 ]
then
    powermenu="./rofi-power-menu"
else
    powermenu="rofi-power-menu"
fi

options=$($powermenu $@ | xxd)
while [ -n "$options" ]
do
    choice=$(echo "$options" | xxd -r | $dmenu -p "Power menu" -i -show-icons)
    if [ $? -ne 0 ]
    then
        break
    fi
    options=$($powermenu $@ "$choice" | xxd)
done
