#!/usr/bin/env bash

# This script defines just a mode for rofi instead of being a self-contained
# executable that launches rofi by itself. This makes it more flexible than
# running rofi inside this script as now the user can call rofi as one pleases.
# For instance:
#
#   rofi -show powermenu -modi powermenu:./rofi-power-menu
#
# See README.md for more information.

lockscreen="Lock screen"
switchuser="Switch user"
logout="Log out"
suspend="Suspend"
hibernate="Hibernate"
reboot="Reboot"
shutdown="Shut down"

# Ask for confirmation for actions that are irreversible
confirmReboot="Yes, reboot"
confirmShutdown="Yes, shut down"
confirmLogout="Yes, log out"
cancel="No, cancel"

# Default options to show
show="$shutdown\n$reboot\n$suspend\n$hibernate\n$logout\n$lockscreen\n"

# Parse command-line options
parsed=$(getopt --options="" --longoptions=options: --name "$0" -- "$@")
if [ $? -ne 0 ]; then
    echo 'Terminating...' >&2
    exit 1
fi
eval set -- "$parsed"
unset parsed
while true; do
    case "$1" in
        "--options")
            IFS='/' read -ra options <<< "$2"
            show=""
            for option in "${options[@]}"; do
                case $option in
                    "lockscreen")
                        show="$show$lockscreen\n" ;;
                    "logout")
                        show="$show$logout\n" ;;
                    "suspend")
                        show="$show$suspend\n" ;;
                    "hibernate")
                        show="$show$hibernate\n" ;;
                    "reboot")
                        show="$show$reboot\n" ;;
                    "shutdown")
                        show="$show$shutdown\n" ;;
                    *)
                        >&2 echo "Invalid option: $option"
                        exit 1
                        ;;
                esac
            done
            shift 2
            continue
            ;;
        "--")
            shift
            break
            ;;
        *)
            echo "Internal error" >&2
            exit 1
            ;;
    esac
done

if [ -z "$1" ]
then
    printf "$show"
else
    selection=$@
    case $selection in
        $lockscreen)
            loginctl lock-session $XDG_SESSION_ID &> /dev/null
            ;;
        $switchuser)
            # TODO: I suppose this is window manager dependent?
            >&2 echo "User switching not implemented yet"
            ;;
        $logout)
            echo $confirmLogout
            echo $cancel
            ;;
        $confirmLogout)
            loginctl terminate-session $XDG_SESSION_ID &> /dev/null
            ;;
        $suspend)
            systemctl suspend &> /dev/null
            ;;
        $hibernate)
            systemctl hibernate &> /dev/null
            ;;
        $reboot)
            echo $confirmReboot
            echo $cancel
            ;;
        $confirmReboot)
            systemctl reboot &> /dev/null
            ;;
        $shutdown)
            echo $confirmShutdown
            echo $cancel
            ;;
        $confirmShutdown)
            systemctl poweroff &> /dev/null
            ;;
        $cancel)
            exit 0
            ;;
        *)
            >&2 echo "Invalid choice."
            exit 1
            ;;
    esac
fi
